### ISSUE TITLE
Derive own @node polyfills

### ISSUE THREAD

**Issue by alexisvincent** [alexisvincent/systemjs-config-builder#1]
At the moment, everything works if you use jspm to install the @node polyfills. But this still requires you to have JSPM installed. 

Normally we would just be able to install the jspm-nodelibs-* packages, but these don't follow the npm conventions. For example, jspm-nodelibs-buffer has the following `package.json`:
```json
{
  "main": "buffer.js",
  "name": "jspm-nodelibs-buffer",
  "version": "0.2.0",
  "registry": "github",
  "map": {
    "./buffer.js": {
      "node": "@node/buffer",
      "browser": "buffer-browserify"
    }
  },
  "dependencies": {
    "buffer-browserify": "npm:buffer@^4.0.0"
  },
  "jspmNodeConversion": false
}
```

Notice the dependency mapping. This causes npm to fail and yarn to do weird things. So I need to create forks of all these libs, and ideally make this automated so that whenever the underlying package changes, we just rebuild.

**Comment by alexisvincent** [comment]
@guybedford, unless you know of a better way to handle this?

**Comment by srolel** [comment]
In this case (unsure if it's the same for the other libraries), why not just map it to `buffer-browserify` directly?

**Comment by alexisvincent** [comment]
@Mosho1 I must explore this more. But I think thats not going to work. Purely because if you checkout [jspm-nodelibs-buffer](https://github.com/jspm/nodelibs-buffer/blob/master/global.js#L1), it maps buffer.Buffer to the export. Some of the other libs do some more complex stuff. Don't know if this is just JSPM specific. Maybe we can just map to the browserify.

This is my next task to tackle. But if you want to play with it, your help would be very welcome :)

**Comment by alexisvincent** [comment]
So, it turns out jspm-nodelibs-\* work just fine if installed from github. With the exception of buffer. But I have a working fork. 

You can now `yarn add systemjs-nodelibs`. And you will get all the required packages.
