### ISSUE TITLE
Investigate why this doesn't work with yarn

### ISSUE THREAD

**Issue by alexisvincent** [alexisvincent/systemjs-config-builder#2]
Installing via npm works. Yarn does not. 

The problem is that Yarn installs the module with this`package.json`

```json
{
  "name": "string_decoder",
  "version": "0.10.31",
  "description": "The string_decoder module from Node core",
  "main": "index.js",
  "dependencies": {},
  "devDependencies": {
    "tap": "~0.4.8"
  },
  "scripts": {
    "test": "tap test/simple/*.js"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/rvagg/string_decoder.git"
  },
  "homepage": "https://github.com/rvagg/string_decoder",
  "keywords": [
    "string",
    "decoder",
    "browser",
    "browserify"
  ],
  "license": "MIT"
}
```

to `node_modules/string_decoder-browserify` instead of `node_modules/string_decoder`.

This is different to the npm behaviour, which works as expected.

@thejameskyle maybe you can help with this?

to reproduce,

```
npm install
cd test
npm install or yarn install
jspm install
npm run config
``` 

the above breaks if you installed via yarn

**Comment by jamiebuilds** [comment]
Please open an issue in Yarn when you discover bugs

**Comment by jamiebuilds** [comment]
Also there doesn't appear to be any problem with Yarn as you describe with installing the `string_decoder` package

**Comment by alexisvincent** [comment]
@thejameskyle Thanks, yeah, I added you as an after thought. Actually meant to investigate this myself. 

It seems the issue was in an older version of yarn, and it persisted through to this version because the lock file remained. Deleting that and doing a fresh `yarn install` worked.
