### ISSUE TITLE
NPM shrinkwrap yarn.lock as source config?

### ISSUE THREAD

**Issue by colmbrady** [alexisvincent/systemjs-config-builder#7]
Hi Guys, 

Wondering your thoughts on this ...

I can see an usecase for generating the systemjs from an npm shrinkwrap file (or yarn.lock file) and not by walking the node_modules dependencies. If you want a consistently repeatable systemjs config file then - it's a better option than trusting developers (or C.I environments) node_modules installs.

When people use optimistic semver in node modules, it can obviously have the side effect that different devs are developing on the same NPM module, but with a different set of downstream dependencies. This can be a disaster for sane release management.

If the systemjs config file was produced from a stable dependency tree that can be versioned, e.g. yarn.lock or npm shrinkwrap - then I could see this been more useful.

**Comment by alexisvincent** [comment]
@colmbrady That's the approach I first took, but switched to tracing node_modules for the following reasons.

- Reading the lock file, would simply skip the first pass where we generate the tree (like 50ms). We then need to analyze the actual packages in node_modules to generate a suitable package config entry. So we anyway need to analyze node_modules (slow)
- using shrink wrap or yarn lock, actually guarantees a deterministic node_modules layout. So if you use either of these locking mechanisms, your CI will produce the same node_modules, and so the config will be valid. Thus the config generation is still deterministic. 
- I don't want to only be able to trace the tree from a lock file as this would mean anyone just testing (without a lock file), would not be able to use the generator (this approach makes it more general)

If theres anything I've missed let me know and we can reopen this issue.

Note, that I'm hoping to submit a PR to yarn to include this config generator, so we would use the lock file in that case.

**Comment by colmbrady** [comment]
Makes sense. Thank you.

**Comment by alexisvincent** [comment]
@colmbrady But thanks for the thoughts, great to have people thinking about this stuff :)

**Comment by alexisvincent** [comment]
@colmbrady @jonaskello is playing with this in #15
